### ISSUE TITLE
Fatal error when attempting to add new listing or edit. 

### ISSUE THREAD

**Issue by Tototex** [lddweb/ldd-directory-lite#125]
I can "view" and "quick edit". If I attempt to "edit" or "add listing", I get the error below;

"There has been a critical error on this website. Please check your site admin email inbox for instructions.
Learn more about troubleshooting WordPress."

WordPress version 6.0.3
Active theme: Astra (version 3.9.2)
Current plugin: LDD Directory Lite (version 3.7)
PHP version 7.4.32

Error Details
=============
An error of type E_ERROR was caused in line 13 of the file /home3/newposi7/public_html/wp-content/plugins/ldd-directory-lite/includes/cmb/includes/types/CMB2_Type_Text.php. Error message: Uncaught Error: Class 'CMB2_Type_Counter_Base' not found in /home3/newposi7/public_html/wp-content/plugins/ldd-directory-lite/includes/cmb/includes/types/CMB2_Type_Text.php:13
Stack trace:
#0 /home3/newposi7/public_html/wp-content/plugins/ldd-directory-lite/includes/cmb/includes/helper-functions.php(44): include_once()
#1 [internal function]: cmb2_autoload_classes('CMB2_Type_Text')
#2 /home3/newposi7/public_html/wp-content/plugins/ldd-directory-lite/includes/cmb/includes/types/CMB2_Type_Colorpicker.php(13): spl_autoload_call('CMB2_Type_Text')
#3 /home3/newposi7/public_html/wp-content/plugins/ldd-directory-lite/includes/cmb/includes/helper-functions.php(44): include_once('/home3/newposi7...')
#4 [internal function]: cmb2_autoload_classes('CMB2_Type_Color...')
#5 /home3/newposi7/public_html/wp-includes/class-wp-hook.php(307): spl_autoload_call('CMB2_Type_Color...')
#6 /home3/newposi7/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#7 /home3/newposi7/public_html/wp-includes/pl

**Comment by Tototex** [comment]
I did review the file in an attempt to edit the code, but could not think of a way to resolve the issue. 

I did uninstall the plugin and reinstall. Was hoping the existing listings would still be there but they were all deleted. Even in that state, I attempted to create a new listing and got the same error. 

To restore the missing listings, I restored the backup. Listings are back, still getting the error. 

Any help would be greatly appreciated!

**Comment by pixelpusherongit** [comment]
PHP 7.4.16
Same problem here. Been using for some time but just noticed we can't add new listings due to missing inputs. 

- Disabled all wordpress plugins.
- Confirmed theme update and compability
- checked PHP/PEAR setup
 I haven't been able to figure this out yet.

**Comment by pixelpusherongit** [comment]
Reverting to previous version 2.6.4 solved my issue. Waiting for developer to fix.
